name: Label PR
on:
  pull_request:
    types: [opened, edited]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: netlify/pr-labeler-action@v1
        if: startsWith(github.event.pull_request.title, 'fix')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'type: bug'
      - uses: netlify/pr-labeler-action@v1
        if: startsWith(github.event.pull_request.title, 'chore')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'type: chore'
      - uses: netlify/pr-labeler-action@v1
        if: startsWith(github.event.pull_request.title, 'feat')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'type: feature'
